package co.pragra.learning.selenium.framework.testcases;

import co.pragra.learning.selenium.framework.data.ExcelDataProvider;
import co.pragra.learning.selenium.framework.drivermanager.DriverManager;
import co.pragra.learning.selenium.framework.pages.AIEducationGoals;
import co.pragra.learning.selenium.framework.pages.AIFirstSectionPage;
import co.pragra.learning.selenium.framework.pages.AIMedicalInfoPage;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import java.util.concurrent.TimeUnit;

public class AdditionalInformationTest {

 WebDriver driver = DriverManager.getDriver();

 @Test(enabled = true, dataProviderClass = ExcelDataProvider.class,dataProvider ="additionalInfoProvider")
 public void testAdditionalInfo(Object [] data) throws InterruptedException {

  AIEducationGoals eduGoalsPage = new AIEducationGoals(driver);
  AIFirstSectionPage firstSecPage = new AIFirstSectionPage(driver);
  AIMedicalInfoPage medicalInfoPage = new AIMedicalInfoPage(driver);

  driver.manage().timeouts().pageLoadTimeout(20, TimeUnit.SECONDS);
Thread.sleep(8000);
  firstSecPage.clinkOnAddInfoLink();
  Thread.sleep(5000);
  //page.enterCitizenshipp((String)data[0]);
  firstSecPage.enterParentAgent((String)data[1]);
  firstSecPage.enterSchoolInvoice((String)data[2]);
  firstSecPage.enterEmailInvoice((String)data[3]);
  firstSecPage.enterMethodInterview((String)data[4]);
  firstSecPage.enteriD((Object) data[5]);
  firstSecPage.entersocialMedia((String)data[6]);
  firstSecPage.enteriDSocialMedia((Object) data[7]);

  eduGoalsPage.enterCGrade(data[8]);
  eduGoalsPage.enterAGrade((String)data[9]);
  eduGoalsPage.clickOnYesBtn();
  eduGoalsPage.Agency((String)data[10]);
  eduGoalsPage.AgencyFName((String)data[11]);
  eduGoalsPage.AgencyEmail((String)data[12]);
  eduGoalsPage.AgencyAddress((String)data[13]);
  eduGoalsPage.AgencyCity((String)data[14]);
  eduGoalsPage.AgencyProvince((String)data[15]);
  eduGoalsPage.AgencyCountry((String)data[16]);
  eduGoalsPage.AgencyPostalCode(data[17]);
  eduGoalsPage.Counsellor((String)data[18]);
  eduGoalsPage.CounsellorEmail(data[19]);
  eduGoalsPage.CounsellorPhone(data[20]);
  eduGoalsPage.CurrentSchool((String)data[21]);
  eduGoalsPage.SchoolWebsite((String)data[22]);
  eduGoalsPage.SeptemberRadioBtn();
  eduGoalsPage.SelectYear(data[23]);
  eduGoalsPage.OthBtn();
  eduGoalsPage.FromDate((String)data[24]);
  eduGoalsPage.ToDate((String)data[25]);
  eduGoalsPage.SchoolAttended((String)data[26]);
  eduGoalsPage.CanadianSchool((String)data[27]);
  eduGoalsPage.SchoolGoal((String)data[28]);
  eduGoalsPage.OtherSchoolGoal((String)data[29]);
  eduGoalsPage.EngYears(data[30]);
  eduGoalsPage.ieltsYesBtn();
  eduGoalsPage.ieltsRslt(data[31]);
  eduGoalsPage.toeflYesBtn();
  eduGoalsPage.toeflRslt(data[32]);
  eduGoalsPage.ooptNoBtn();
  eduGoalsPage.slepNoBtn();
  eduGoalsPage.cambridgeNoBtn();
  eduGoalsPage.placementNoBtn();
  eduGoalsPage.otherNoBtn();
  eduGoalsPage.HearAboutSchool((String)data[33]);
  eduGoalsPage.CompleteHighSchool();
  eduGoalsPage.SpecialLearningNeeds((String)data[34]);
  eduGoalsPage.FrndOrFamily();
  eduGoalsPage.EducationFair();
  eduGoalsPage.CanadianConsulate();
  eduGoalsPage.CanadianEduCenter();
  eduGoalsPage.OtBtn();
  eduGoalsPage.OtherField((String)data[35]);
  eduGoalsPage.Newspaper((String)data[36]);

  firstSecPage.scrollpage();
  //medicalInfoPage.scrollingPage();
  medicalInfoPage.clickOnAllerYesBtn();
  //Thread.sleep(5000);
  //medicalInfoPage.foodCheckbox();
  medicalInfoPage.foodTextarea((String) data[37]);
  medicalInfoPage.animalCheckbox();
  medicalInfoPage.animalTextarea((String) data[38]);
//      medicalInfoPage.medicationsCheckbox();
  medicalInfoPage.medicationsTextarea((String)data[39]);
  medicalInfoPage.insectCheckboxx();
  medicalInfoPage.insectAllerTextarea((String)data[40]);
//        medicalInfoPage.otherCheckboxx();
  medicalInfoPage.otherTextarea((String)data[41]);
  medicalInfoPage.clickstudAfYesBtn();
  medicalInfoPage.clickEpiPenYesBtn();
  medicalInfoPage.clickAnalReacYesBtn();
  medicalInfoPage.clickHealthConcernYesBtn();
  medicalInfoPage.clickHealthConcernExp((String)data[42]);
//        medicalInfoPage.clickMentalYesBtn();
  medicalInfoPage.clickMentalExp((String)data[43]);
  medicalInfoPage.clickConcernLifeYesBtn();
  medicalInfoPage.clickConcernLifeExpl((String)data[44]);
  medicalInfoPage.clickMedicatYesBtn();
  medicalInfoPage.clickMedicatRegExp((String)data[45]);
  medicalInfoPage.clickSelfMedYesBtn();
  medicalInfoPage.clickSmokeYesBtn();
  medicalInfoPage.FromDateTetnusShot((String)data[46]);
  medicalInfoPage.clickAnyOfTheFollowingYesBtn();
  medicalInfoPage.clickVision();
  medicalInfoPage.clickDigestiveTroubles();
//medicalInfoPage.clickAsthmaRespiratory();
//   medicalInfoPage.clickDiabetes();
  Thread.sleep(3000);
//        medicalInfoPage.clickEpilepsys();
//        medicalInfoPage.clickFrequentHeadaches();
//        medicalInfoPage.clickHistoryOfSeizures();
//        medicalInfoPage.clickSkinDisorder();
//     medicalInfoPage.clickIllnessesNone();
//    medicalInfoPage.clickMeasles();
//        medicalInfoPage.clickScarletFever();
//        medicalInfoPage.clickCancerTumors();
//        medicalInfoPage.clickMumps();
//        medicalInfoPage.clickThyroidDisease();
//        medicalInfoPage.clickRheumaticFever();
//        medicalInfoPage.clickHepatitis();
//        medicalInfoPage.clickRubella();
//        medicalInfoPage.clickChickenPox();
//        medicalInfoPage.clickOtherIllnessesCheck();
  medicalInfoPage.clickOtherIllnessesField((String)data[47]);
  medicalInfoPage.clickOtherIllnessesDescription((String)data[48]);
  medicalInfoPage.clickSufferedCheckYesBtn();
  medicalInfoPage.clickDepression();
  medicalInfoPage.clickSevereMoodSwings();
  medicalInfoPage.clickEatingDis();
  medicalInfoPage.clickObsessiveCompulsive();
  medicalInfoPage.clickDifficultiesConcentrating();
  medicalInfoPage.clickLearningDisability();
  medicalInfoPage.clickDrugAlcoholDependency();
  medicalInfoPage.clickMoreInformation((String)data[49]);
  medicalInfoPage.clickOtherMedicalConditionsYes((Object)data[50]);
//        medicalInfoPage.clickOtherMedicalConditionExpl((String)data[51]);
  medicalInfoPage.clickHealthIssues((String)data[52]);
  medicalInfoPage.clickFamilyDoctorNames((String)data[53]);
  medicalInfoPage.clickFamilyPhoneNumber(data[54]);
  medicalInfoPage.clickDentistName((String)data[55]);
  medicalInfoPage.clickDentistPhoneNumber(data[56]);
  medicalInfoPage.clickDPTBHIBHIB();
  medicalInfoPage.DPTBHIBHIBDate((String)data[57]);
  medicalInfoPage.clickBooster();
  medicalInfoPage.BoosterDate((String)data[58]);
  medicalInfoPage.clickMMR();
  medicalInfoPage.MMRDate((String)data[59]);
  medicalInfoPage.clickhepatitisB();
  medicalInfoPage.HepatitisBDate((String)data[60]);
  //Thread.sleep(5000);
//  medicalInfoPage.clickDisclosureAgreeInfor();
//  Thread.sleep(5000);
//  medicalInfoPage.clickDisclosureContactIf();
//  medicalInfoPage.clickDisclosureAwareOutbrake();
//  medicalInfoPage.clickDisclosureAwareChildNeeds();
//  medicalInfoPage.clickDisclosureAwareUpdate();
//  Thread.sleep(8000);
 }
}
